name: Sync Indexed Collections

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  run-sync:
    name: Run Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'          

      - name: Install dependencies
        working-directory: .github/scripts/sync
        run: uv sync
    
      - name: Run script
        env:
          CHROMA_TENANT_UUID: ${{ secrets.CHROMA_TENANT_UUID }}
          CHROMA_API_KEY: ${{ secrets.CHROMA_API_KEY }}
          AUTH_API_KEY: ${{ secrets.AUTH_API_KEY }}
        run: uv run .github/scripts/sync/main.py
