name: Sync Indexed Collections

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  run-sync:
    name: Run Sync
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'          

      - name: Install dependencies
        working-directory: .github/scripts/sync
        run: uv sync
    
      - name: Run script
        working-directory: .github/scripts/sync
        env:
          CHROMA_TENANT_UUID: ${{ secrets.CHROMA_TENANT_UUID }}
          CHROMA_API_KEY: ${{ secrets.CHROMA_API_KEY }}
        run: uv run main.py

      - name: Check for changes
        id: git-check
        run: |
          if git diff --quiet versions.json; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.email "bot@trychroma.com"
          git config --global user.name "Chroma Bot"
          git add versions.json
          git commit -m "$(cat <<'EOF'
          [AUTOGEN] update versions.json from sync script
          EOF
          )"
          git push origin main
